#cloud-config
password: ubuntu
ssh_pwauth: true
users:
  - name: ubuntu
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: false
    gecos: Ubuntu
    groups: sudo
    homedir: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ${SSH_PUBLIC_KEY}
chpasswd:
  expire: false
  users:
    - {name: ubuntu, password: ubuntu, type: text}

package_update: true
package_upgrade: true
packages:
  # Packages for a minimal Ubuntu desktop environment
  - fonts-ubuntu
  - gdm3
  - gnome-shell
  - gnome-shell-extension-ubuntu-dock
  - gnome-terminal
  - gsettings-ubuntu-schemas
  - policykit-desktop-privileges
  - ubuntu-settings
  - yaru-theme-gtk
  - yaru-theme-icon
  # To enable SSH access
  - openssh-server
  # To forward SSH over VSOCK
  - socat
  # For shared clipboard (useful for debugging)
  - spice-vdagent
  # To sync the system time after restoring snapshots
  - systemd-timesyncd
write_files:
  # Configure dconf
  - path: /etc/dconf/db/local.d/00-e2e-tests
    content: |
      # Disable automatic suspend when plugged in
      [org/gnome/settings-daemon/plugins/power]
      sleep-inactive-ac-type='nothing'
      sleep-inactive-ac-timeout=0

      # Disable screen blanking
      [org/gnome/desktop/session]
      idle-delay=uint32 0

      # Use larger text for better OCR results
      [org/gnome/desktop/interface]
      text-scaling-factor=1.25

  # Bind sshd to VSOCK socket (only needed with systemd < 256)
  - path: /etc/systemd/system/sshd-vsock.service
    content: |
      [Unit]
      Description=SSH over VSOCK
      After=network.target

      [Service]
      ExecStart=/usr/bin/socat VSOCK-LISTEN:22,reuseaddr,fork TCP:127.0.0.1:22
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

  # Export the journal via VSOCK (only needed with systemd < 256)
  - path: /etc/systemd/system/journal-vsock-export.service
    content: |
      [Unit]
      Description=Exports the journal over VSOCK
      After=systemd-journald.service
      After=network.target
      Requires=network.target
      RestartSec=1
      # Disable rate limiting
      StartLimitIntervalSec=0

      [Service]
      Type=simple
      ExecStart=/bin/bash -o pipefail -c 'journalctl -b --lines=all -o export -f | socat - VSOCK-CONNECT:2:52000'
      OOMScoreAdjust=-1000
      Restart=always

      [Install]
      WantedBy=basic.target

runcmd:
  # Update dconf database
  - dconf update
  # Disable Apport to avoid popups which interfere with tests
  - sed -i 's/enabled=1/enabled=0/' /etc/default/apport
  - systemctl mask --now apport.service
  # Disable systemd-networkd-wait-online to speed up boot time
  - sudo systemctl mask systemd-networkd-wait-online.service
  # Enable our systemd services
  - sudo systemctl enable sshd-vsock.service
  - sudo systemctl enable journal-vsock-export.service
  # Avoid APT downloads and upgrades during the tests
  - sudo systemctl mask apt-daily.service
  - sudo systemctl mask apt-daily.timer
  - sudo systemctl mask apt-daily-upgrade.service
  - sudo systemctl mask apt-daily-upgrade.timer
  - sudo systemctl mask unattended-upgrades.service
  - sudo rm -f /etc/apt/apt.conf.d/20auto-upgrades /etc/apt/apt.conf.d/50unattended-upgrades

final_message: "Provisioning finished after $UPTIME seconds"

power_state:
  mode: poweroff
  message: Shutting down instance after initial setup
  condition: True
  timeout: 30
